### ISSUE TITLE
Error in the new master branch

### ISSUE THREAD

**Issue by davidhsv** [RasaHQ/helpdesk-assistant#38] opened 2020-11-05 21:56 UTC
ERROR    rasa.core.nlg.interpolator  - Failed to fill utterance template '/inform{"priority":"low"}'. Tried to replace '"priority":"low"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):
  File "/home/david/desenvolvimento/projetos/grupo8/venv/lib/python3.7/site-packages/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
    text = text.format(values)
KeyError: '"priority":"low"'
2020-11-05 18:53:51 ERROR    rasa.core.nlg.interpolator  - Failed to fill utterance template '/inform{"priority":"medium"}'. Tried to replace '"priority":"medium"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):
  File "/home/david/desenvolvimento/projetos/grupo8/venv/lib/python3.7/site-packages/rasa/core/nlg/interpolator.py", line 28, in interpolate_text
    text = text.format(values)
KeyError: '"priority":"medium"'
2020-11-05 18:53:51 ERROR    rasa.core.nlg.interpolator  - Failed to fill utterance template '/inform{"priority":"high"}'. Tried to replace '"priority":"high"' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):

**Comment by sara-tagger** [comment] 2020-11-06 07:00
Thanks for the issue, @samsucik will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by samsucik** [comment] 2020-11-06 08:20
Hey @davidhsv, this looks like the string `/inform{"priority":"low"}` gets misidentified as a [response with variables](https://rasa.com/docs/rasa/responses#using-variables-in-responses). First things first, which version of Rasa do you use? Secondly, do you know where the string is coming from? If it's in your NLU data, could you share the relevant part of the data file? That could help us understand why the string is treated as a response.

**Comment by davidhsv** [comment] 2020-11-06 13:37
I'm using the 2.0.3 version, and the nlu data is from the branch master of the help-desk-assistant. To reproduce, clone the code from this repo, rasa shell, and answer hi, open an incident, rmail@djjd.com, and choose the priority

**Comment by samsucik** [comment] 2020-11-09 08:47
Oh, sorry @davidhsv, I didn't notice the repo and thought this issue belonged to the `rasa` one. I've been able to reproduce this and it looks like a bug. Thanks a lot for reporting! I believe @erohmensing will fix it.

**Comment by erohmensing** [comment] 2020-11-12 19:10
I'm going to close this as it's a duplicate. Sorry for the annoying error, it should be gone soon! But it won't affect the performance of your assistant. 🙂

**Closed by erohmensing** 2020-11-12 19:10 UTC
